services:
    php:
        build:
            context: docker/php
        container_name: app-php
        volumes:
            - ./:/var/www/html/nota-por-nota
        networks:
            - nota-por-nota-network

    nginx:
        build:
            context: docker/nginx
        container_name: app-nginx
        volumes:
            - ./:/var/www/html/nota-por-nota
        ports:
            - "8000:80"
        networks:
            - nota-por-nota-network

    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning
    #        volumes:
    #            - cache:/dat

    postgres:
        container_name: app-postgres
        image: postgres:17
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=nota-por-nota
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./.postgres:/var/lib/postgres/data
        networks:
            - nota-por-nota-network

    mailpit:
        image: axllent/mailpit
        container_name: app-mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
        restart: unless-stopped
        volumes:
            - ./data:/data
        environment:
            MP_MAX_MESSAGES: 5000
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - nota-por-nota-network

    soketi:
        container_name: app-soketi
        restart: unless-stopped
        image: 'quay.io/soketi/soketi:0.17-16-alpine'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
        environment:
            - SOKETI_DEBUG='${DEBUG:-1}'
            - METRICS_SERVER_PORT=${SOKETI_METRICS_SERVER_PORT:-9601}
            - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES:-false}
        networks:
            - nota-por-nota-network

networks:
    nota-por-nota-network:
        driver: bridge

volumes:
    mysql-data: